### ISSUE TITLE
红黑树的实现是错的，不能用golang 的nil 作为树的NIL节点

### ISSUE THREAD

**Issue by xkeyideal** [liyue201/gostl#2]

**Comment by liyue201** [comment]
New的时候使用WithKeyComparator，传入自己实现的比较函数就可以了

**Comment by liyue201** [comment]
默认的比较函数，只支持key都是go内建的数据类型，且类型一致

**Comment by xkeyideal** [comment]
和Compare函数没有关系。

https://github.com/liyue201/gostl/blob/master/ds/rbtree/rbtree.go#L141

这行代码不能用  z.parent != nil， 不能用语言自带的nil作为红黑树的nil，否则删除节点的时候会违反性质5

如果不信的话，你去删除一个红黑树中某个节点，该节点的左子树为空，右子树非空。

至于为什么可以把算法导论拿出来看看

**Comment by xkeyideal** [comment]
etcd v3.4版本之前的区间树犯了和你一样的错误

**Comment by liyue201** [comment]
getColor函数已经处理了，go语言的nil就是黑色节点

**Comment by liyue201** [comment]
> etcd v3.4版本之前的区间树犯了和你一样的错误

没看出来有什么不一样。我看了etcd的代码，增加了一个sentinel的节点，它只是用来表示黑色而已，并有实际意义，也没有修改它的地方，为什么不用全局变量。

**Comment by xkeyideal** [comment]
首先不能使用全局变量，因为etcd里面创建了多颗树。
其次sentinel节点就是NIL节点
最后你还没有彻底理解红黑树

如果用golang的nil作为树的NIL节点，那么怎么标识颜色呢？ 
当删除操作的时候怎么做`黑+黑`呢？

所以必然会导致删除的时候，造成树不符合红黑树的性质5

结论：只要用语言的nil或null 作为红黑树的NIL节点，那么写出来的代码都是错的

**Comment by liyue201** [comment]
> 首先不能使用全局变量，因为etcd里面创建了多颗树。
> 其次sentinel节点就是NIL节点
> 最后你还没有彻底理解红黑树
> 
> 如果用golang的nil作为树的NIL节点，那么怎么标识颜色呢？
> 当删除操作的时候怎么做`黑+黑`呢？
> 
> 所以必然会导致删除的时候，造成树不符合红黑树的性质5
> 
> 结论：只要用语言的nil或null 作为红黑树的NIL节点，那么写出来的代码都是错的

一个变量如果永远不需要修改，作为全局变量有什么问题？nil仅仅是个标记黑色节点而已。这个函数已经实现了将nil作为黑节点处理
https://github.com/liyue201/gostl/blob/f8893373a6bf4e262d8dd2ad11cc7263a487956a/ds/rbtree/rbtree.go#L391

**Comment by xkeyideal** [comment]
随便你吧，已经给你提醒到了，不仅仅是这样的，树的NIL节点需要作为一个指针的，删除的时候，旋转的时候会有用，至于你改不改随意吧。

**Comment by angon823** [comment]
> 首先不能使用全局变量，因为etcd里面创建了多颗树。
> 其次sentinel节点就是NIL节点
> 最后你还没有彻底理解红黑树
> 
> 如果用golang的nil作为树的NIL节点，那么怎么标识颜色呢？
> 当删除操作的时候怎么做`黑+黑`呢？
> 
> 所以必然会导致删除的时候，造成树不符合红黑树的性质5
> 
> 结论：只要用语言的nil或null 作为红黑树的NIL节点，那么写出来的代码都是错的

https://zh.wikipedia.org/wiki/%E7%BA%A2%E9%BB%91%E6%A0%91
wiki百科上没有按照算法导论上黑+黑的方式来讨论， 明天试试你说的 删除一个红黑树中某个节点，该节点的左子树为空，右子树非空。

**Comment by xkeyideal** [comment]
@angon823 
只要记着红黑树的五个特性即可，如果不考虑黑+黑的情况，那么当遇到`一个红黑树中某个节点，该节点的左子树为空，右子树非空`` 那么它必然不再是一颗红黑树。

另外从来没有一本正确说明红黑树的教材，会把编程语言的null当做红黑树的NIL节点，所以只要看到的，实现的红黑树一律是错的，它解决不了黑+黑的case

**Comment by angon823** [comment]
> @angon823
> 只要记着红黑树的五个特性即可，如果不考虑黑+黑的情况，那么当遇到`一个红黑树中某个节点，该节点的左子树为空，右子树非空` 那么它必然不再是一颗红黑树。
> 
> 另外从来没有一本正确说明红黑树的教材，会把编程语言的null当做红黑树的NIL节点，所以只要看到的，实现的红黑树一律是错的，它解决不了黑+黑的case

我看了下C++ STL 和 JDK8 TreeMap的实现，
STL 是用了一个_IsNil 来表示是否是nil节点，但是JDK用的是语言的null 
http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/TreeMap.java#l505

> 一个红黑树中某个节点，该节点的左子树为空，右子树非空

能否举一个例子来上面上面的情况

**Comment by xkeyideal** [comment]
@angon823 
java不了解，自己把源码拿出来，跑一下case呗

**Comment by angon823** [comment]
> @angon823
> java不了解，自己把源码拿出来，跑一下case呗

![image](https://user-images.githubusercontent.com/30118943/88256554-344d8600-ccee-11ea-8323-e2dab5ab0124.png)

删除20是否符合你说的case情况，这个代码删除后仍然是红黑树

**Comment by xkeyideal** [comment]
@angon823 

红黑树的性质5：从任一节点到其每个叶子的所有简单路径都包含相同数目的黑色节点.

性质5，就是通俗说的黑高，这个性质是很多人习惯性写着写着就忽略的

例子: 

![image](https://user-images.githubusercontent.com/6369390/60792585-87fb3900-a198-11e9-97f9-be4c15ee9854.png)

删除节点 514, 再删除节点 11 后，红黑树应该如下：

![image](https://user-images.githubusercontent.com/6369390/60792685-bb3dc800-a198-11e9-9eab-ec20b9d87dec.png)

这个case能跑过，就说明没有问题，只要跑不过的，都说明性质5不满足

**Comment by angon823** [comment]
> 删除节点 514, 再删除节点 11 后，红黑树应该如下：

用这个项目的代码跑的没问题

> 0xc0000489c0 &{parent:0xc000048a00 left:<nil> right:<nil> color:true key:11 value:1} true left
0xc000048a00 &{parent:0xc000048a80 left:0xc0000489c0 right:0xc000048ac0 color:true key:82 value:2} true left
0xc000048b00 &{parent:0xc000048ac0 left:<nil> right:<nil> color:false key:238 value:6} false left
0xc000048ac0 &{parent:0xc000048a00 left:0xc000048b00 right:0xc000048b40 color:true key:261 value:5} true right
0xc000048b40 &{parent:0xc000048ac0 left:<nil> right:<nil> color:false key:292 value:7} false right
0xc000048a80 &{parent:<nil> left:0xc000048a00 right:0xc000048c00 color:true key:383 value:4} true root
0xc000048b80 &{parent:0xc000048a40 left:<nil> right:<nil> color:true key:410 value:8} true left
0xc000048a40 &{parent:0xc000048c00 left:0xc000048b80 right:0xc000048bc0 color:true key:510 value:3} true left
0xc000048bc0 &{parent:0xc000048a40 left:<nil> right:<nil> color:true key:514 value:9} true right
0xc000048c00 &{parent:0xc000048a80 left:0xc000048a40 right:0xc000048c40 color:false key:647 value:10} false right
0xc000048c80 &{parent:0xc000048c40 left:<nil> right:<nil> color:true key:815 value:12} true left
0xc000048c40 &{parent:0xc000048c00 left:0xc000048c80 right:0xc000048cc0 color:true key:830 value:11} true right
0xc000048d00 &{parent:0xc000048cc0 left:<nil> right:<nil> color:true key:888 value:14} true left
0xc000048cc0 &{parent:0xc000048c40 left:0xc000048d00 right:0xc000048d40 color:false key:899 value:13} false right
0xc000048d80 &{parent:0xc000048d40 left:<nil> right:<nil> color:false key:963 value:16} false left
0xc000048d40 &{parent:0xc000048cc0 left:0xc000048d80 right:<nil> color:true key:972 value:15} true right
删除514
node: 0xc000048bc0, &{parent:0xc000048a40 left:<nil> right:<nil> color:true key:514 value:9}
IsRbTree:  true <nil>
删除11
node: 0xc0000489c0, &{parent:0xc000048a00 left:<nil> right:<nil> color:true key:11 value:1}
IsRbTree:  true <nil>
0xc000048a00 &{parent:0xc000048ac0 left:<nil> right:0xc000048b00 color:true key:82 value:2} true left
0xc000048b00 &{parent:0xc000048a00 left:<nil> right:<nil> color:false key:238 value:6} false right
0xc000048ac0 &{parent:0xc000048a80 left:0xc000048a00 right:0xc000048b40 color:true key:261 value:5} true left
0xc000048b40 &{parent:0xc000048ac0 left:<nil> right:<nil> color:true key:292 value:7} true right
0xc000048a80 &{parent:<nil> left:0xc000048ac0 right:0xc000048c40 color:true key:383 value:4} true root
0xc000048b80 &{parent:0xc000048a40 left:<nil> right:<nil> color:false key:410 value:8} false left
0xc000048a40 &{parent:0xc000048c00 left:0xc000048b80 right:<nil> color:true key:510 value:3} true left
0xc000048c00 &{parent:0xc000048c40 left:0xc000048a40 right:0xc000048c80 color:true key:647 value:10} true left
0xc000048c80 &{parent:0xc000048c00 left:<nil> right:<nil> color:true key:815 value:12} true right
0xc000048c40 &{parent:0xc000048a80 left:0xc000048c00 right:0xc000048cc0 color:false key:830 value:11} false right
0xc000048d00 &{parent:0xc000048cc0 left:<nil> right:<nil> color:true key:888 value:14} true left
0xc000048cc0 &{parent:0xc000048c40 left:0xc000048d00 right:0xc000048d40 color:true key:899 value:13} true right
0xc000048d80 &{parent:0xc000048d40 left:<nil> right:<nil> color:false key:963 value:16} false left
0xc000048d40 &{parent:0xc000048cc0 left:0xc000048d80 right:<nil> color:true key:972 value:15} true right


你注意下 getColor这个函数是把nil节点也当做黑色处理的[https://github.com/liyue201/gostl/blob/f8893373a6bf4e262d8dd2ad11cc7263a487956a/ds/rbtree/rbtree.go#L391](url)

**Comment by xkeyideal** [comment]
@angon823 你能把删除后的这个代码跑出来的树打印出来不？
你这给一堆看不懂啊

**Comment by angon823** [comment]
> @angon823 你能把删除后的这个代码跑出来的树打印出来不？
> 你这给一堆看不懂啊

主要注意 `IsRbTree: true`这个输出。。
要我打印出来有点太浪费时间了。。但是输出和你给的图是一样的结构

**Comment by xkeyideal** [comment]
@angon823 
0xc000048a80 &{parent: left:0xc000048a00 right:0xc000048c00 color:true key:383 value:4} true root
删除 514 节点后， root都变成了383还一样？

0xc000048a80 &{parent: left:0xc000048ac0 right:0xc000048c40 color:true key:383 value:4} true root
再删除11节点后，root还是383

没看出来哪里一样

**Comment by xkeyideal** [comment]
@angon823 嗯，case能过，就应该没有问题
