### ISSUE TITLE
单元测试应该断言

### ISSUE THREAD

**Issue by whuhyw** [liyue201/gostl#3]
没有断言的单元测试不是单元测试,没有任何意义.建议用`testify`库或者直接`reflect.DeepEqual`比较下期望值和实际值.

**Comment by whuhyw** [comment]
另外建议定义算法和数据结构对应的接口,将定义和具体的实现分开,方便`gomock`等工具进行`mock`.

**Comment by liyue201** [comment]
interface适当使用就行了，用多了就会很啰嗦

**Comment by whuhyw** [comment]
> interface适当使用就行了，用多了就会很啰嗦

有道理,我们公司要求 100% 覆盖率,所以条件反射了.

**Comment by liyue201** [comment]
写得比较急，单元测试还不完善，后续会整理

**Comment by whuhyw** [comment]
另外有些无关紧要的问题.可以设置一个`FileWatcher`执行`goimports`或`gofmt`避免.更好的做法是设置个 git 的强制策略, 格式化后才提交.
1.包名应该是单个单词.
 ![image](https://user-images.githubusercontent.com/12651781/69786246-fe0a4600-11f4-11ea-9eae-54242dbb423d.png)  
2.尽量不要重命名[标准库的包](https://github.com/liyue201/gostl/blob/master/ds/bloomfilter/bloom.go#L10).
3.对导入的包排序.
...

最后,我也在复习数据结构和算法,向大佬学习!
![image](https://user-images.githubusercontent.com/12651781/69787198-f481dd80-11f6-11ea-93de-3fbde0ce8e2d.png)
