### ISSUE TITLE
线程安全还是协程安全？

### ISSUE THREAD

**Issue by andy-zhangtao** [liyue201/gostl#4]
看到介绍里面，大部分算法标记的都是线程安全。但在具体使用过程中，协程使用场景远远大于线程使用场景，所以向大佬确认一下到底是线程安全还是协程安全？

**Comment by liyue201** [comment]
中文应该是协程安全，但是英语只有threadsafe（线程安全）

**Comment by andy-zhangtao** [comment]
好的。明白了，多谢大佬及时回复

stirlingx <notifications@github.com> 于2020年1月7日周二 下午5:36写道：
