### ISSUE TITLE
MutilMap的删除有BUG

### ISSUE THREAD

**Issue by angon823** [liyue201/gostl#7]
`
func TestMulitMap(t *testing.T) {
	m := NewMultiMap()

	x := []int{20, 40, 50, 50, 35, 60, 70, 80, 120, 140, 50, 2, 5, 60, 50,50,50}
	N := len(x)
	for i := 1; i <= N; i++ {
		m.Insert(x[i-1], i)
	}
	m.Erase(50)
}	
`

试一下上面这个Test

`
--- FAIL: TestMulitMap (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x52274f]

goroutine 19 [running]:
testing.tRunner.func1(0xc0000ea300)
	C:/Go/src/testing/testing.go:792 +0x38e
panic(0x695580, 0x8e9fd0)
	C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/liyue201/gostl/ds/rbtree.(*RbTree).rbFixupLeft(0xc0000468e0, 0x0, 0xc000048d40, 0x0, 0xe, 0xc0000f9e98)
	E:/third/gostl/ds/rbtree/rbtree.go:249 +0x2f
github.com/liyue201/gostl/ds/rbtree.(*RbTree).rbDeleteFixup(0xc0000468e0, 0x0, 0xc000048d40)
	E:/third/gostl/ds/rbtree/rbtree.go:237 +0x95
github.com/liyue201/gostl/ds/rbtree.(*RbTree).Delete(0xc0000468e0, 0xc000048c40)
	E:/third/gostl/ds/rbtree/rbtree.go:225 +0x106
github.com/liyue201/gostl/ds/map.(*MultiMap).Erase(0xc000046900, 0x67e300, 0x72ba68)
	E:/third/gostl/ds/map/multimap.go:62 +0x146
github.com/liyue201/gostl/ds/map.TestMulitMap(0xc0000ea300)
	E:/third/gostl/ds/map/multimap_test.go:18 +0x155
testing.tRunner(0xc0000ea300, 0x6fbc60)
	C:/Go/src/testing/testing.go:827 +0xc6
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:878 +0x363
`

我不确定是红黑树的问题还是Erase时后继迭代问题，可能删除时有两个子节点的情况的处理为删除最先后继使得 mutilateMap Erase时不能简单用后继迭代

**Comment by liyue201** [comment]
迭代删除有问题，删除之后指针变化了

**Comment by angon823** [comment]
> 迭代删除有问题，删除之后指针变化了

你的补丁在删除的时候避免使用了后继节点来迭代，但是我觉得可能下面的方法更好：
不要删除后继指针，而是把后继节点和要删除的节点位置交换（Relink），再把要删除的节点剥出来，这样后继节点不会因为删除而失效

```
func (rb *RbTree) Delete(n *Node) {
	erasedNode := n
	var fixNode, fixNodeParent, pNode *Node

	pNode = erasedNode
	if pNode.left == nil {
		fixNode = pNode.right
	} else if pNode.right == nil {
		fixNode = pNode.right
	} else {
		pNode = successor(n)
		fixNode = pNode.right
	}

	if pNode == erasedNode {
		fixNodeParent = erasedNode.parent
		if fixNode != nil {
			fixNode.parent = fixNodeParent // link up
		}
		if rb.root == erasedNode {
			rb.root = fixNode // link down from root
		} else if fixNodeParent.left == erasedNode {
			fixNodeParent.left = fixNode // link down to left
		} else {
			fixNodeParent.right = fixNode // link down to right
		}
	} else {
		//>> pNode is erasedNode's successor,  swap(pNode, erasedNode)
		erasedNode.left.parent = pNode // link left up
		pNode.left = erasedNode.left   // link successor down
		if pNode == erasedNode.right {
			fixNodeParent = pNode // successor is next to erased
		} else { // successor further down, link in place of erased
			fixNodeParent = pNode.parent // parent is successor's
			if fixNode != nil {
				fixNode.parent = fixNodeParent // link fix up
			}
			fixNodeParent.left = fixNode    // link fix down
			pNode.right = erasedNode.right  // link next down
			erasedNode.right.parent = pNode // right up
		}
		if rb.root == erasedNode {
			rb.root = pNode // link down from root
		} else if erasedNode.parent.left == erasedNode {
			erasedNode.parent.left = pNode // link down to left
		} else {
			erasedNode.parent.right = pNode // link down to right
		}
		pNode.parent = erasedNode.parent                              // link successor up
		pNode.color, erasedNode.color = erasedNode.color, pNode.color // recolor it
	}

	if erasedNode.color == BLACK { // erasing black link, must recolor/rebalance tree
		rb.rbDeleteFixup(fixNode, fixNodeParent)
	}
	rb.size--
}
```

**Comment by liyue201** [comment]
> > 迭代删除有问题，删除之后指针变化了
> 
> 你的补丁在删除的时候避免使用了后继节点来迭代，但是我觉得可能下面的方法更好：
> 不要删除后继指针，而是把后继节点和要删除的节点位置交换（Relink），再把要删除的节点剥出来，这样后继节点不会因为删除而失效
> 
> ```
> func (rb *RbTree) Delete(n *Node) {
> 	erasedNode := n
> 	var fixNode, fixNodeParent, pNode *Node
> 
> 	pNode = erasedNode
> 	if pNode.left == nil {
> 		fixNode = pNode.right
> 	} else if pNode.right == nil {
> 		fixNode = pNode.right
> 	} else {
> 		pNode = successor(n)
> 		fixNode = pNode.right
> 	}
> 
> 	if pNode == erasedNode {
> 		fixNodeParent = erasedNode.parent
> 		if fixNode != nil {
> 			fixNode.parent = fixNodeParent // link up
> 		}
> 		if rb.root == erasedNode {
> 			rb.root = fixNode // link down from root
> 		} else if fixNodeParent.left == erasedNode {
> 			fixNodeParent.left = fixNode // link down to left
> 		} else {
> 			fixNodeParent.right = fixNode // link down to right
> 		}
> 	} else {
> 		//>> pNode is erasedNode's successor,  swap(pNode, erasedNode)
> 		erasedNode.left.parent = pNode // link left up
> 		pNode.left = erasedNode.left   // link successor down
> 		if pNode == erasedNode.right {
> 			fixNodeParent = pNode // successor is next to erased
> 		} else { // successor further down, link in place of erased
> 			fixNodeParent = pNode.parent // parent is successor's
> 			if fixNode != nil {
> 				fixNode.parent = fixNodeParent // link fix up
> 			}
> 			fixNodeParent.left = fixNode    // link fix down
> 			pNode.right = erasedNode.right  // link next down
> 			erasedNode.right.parent = pNode // right up
> 		}
> 		if rb.root == erasedNode {
> 			rb.root = pNode // link down from root
> 		} else if erasedNode.parent.left == erasedNode {
> 			erasedNode.parent.left = pNode // link down to left
> 		} else {
> 			erasedNode.parent.right = pNode // link down to right
> 		}
> 		pNode.parent = erasedNode.parent                              // link successor up
> 		pNode.color, erasedNode.color = erasedNode.color, pNode.color // recolor it
> 	}
> 
> 	if erasedNode.color == BLACK { // erasing black link, must recolor/rebalance tree
> 		rb.rbDeleteFixup(fixNode, fixNodeParent)
> 	}
> 	rb.size--
> }
> ```

嗯，这个好，有时间再改一下
